// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsrIc4zjCztj-_sf5zIRrtY6zjWO9iT38',
    appId: '1:491829647993:web:140a828ec95da8df9752a8',
    messagingSenderId: '491829647993',
    projectId: 'kfahi-4e98a',
    authDomain: 'kfahi-4e98a.firebaseapp.com',
    storageBucket: 'kfahi-4e98a.appspot.com',
    measurementId: 'G-89XJZ8YH5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIwUAo3EP7IB4xhm2ppKwXOD6ZaDoEpL4',
    appId: '1:491829647993:android:8840be630c594d109752a8',
    messagingSenderId: '491829647993',
    projectId: 'kfahi-4e98a',
    storageBucket: 'kfahi-4e98a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsg9-xO98APYqbz9bYogFGhTvxT94lnrs',
    appId: '1:491829647993:ios:1d62d00bf05180c99752a8',
    messagingSenderId: '491829647993',
    projectId: 'kfahi-4e98a',
    storageBucket: 'kfahi-4e98a.appspot.com',
    iosBundleId: 'com.example.kfahi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsg9-xO98APYqbz9bYogFGhTvxT94lnrs',
    appId: '1:491829647993:ios:1d62d00bf05180c99752a8',
    messagingSenderId: '491829647993',
    projectId: 'kfahi-4e98a',
    storageBucket: 'kfahi-4e98a.appspot.com',
    iosBundleId: 'com.example.kfahi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsrIc4zjCztj-_sf5zIRrtY6zjWO9iT38',
    appId: '1:491829647993:web:69053b718ab450a59752a8',
    messagingSenderId: '491829647993',
    projectId: 'kfahi-4e98a',
    authDomain: 'kfahi-4e98a.firebaseapp.com',
    storageBucket: 'kfahi-4e98a.appspot.com',
    measurementId: 'G-1G587RNPVB',
  );
}
